export class CreateVehicleTypeDto {
  type_name?: string;
  description?: string;
  max_luggage?: number;
  max_passengers?: number;
  base_fare?: number;
  per_km_rate?: number;
  per_minute_rate?: number;
  pricing_model?: 'STRAIGHT' | 'INCLUDED';
  included_km?: number;
  included_minutes?: number;
  extra_km_rate?: number;
  extra_minute_rate?: number;
  waiting_minutes_free?: number;
  waiting_rate?: number;
  hourly_rate?: number;
  hourly_included_km?: number;
  min_booking_hours?: number;
  free_waiting_standard?: number;
  free_waiting_domestic?: number;
  free_waiting_international?: number;
  waypoint_fee?: number;
  waypoint_fee_type?: 'FIXED' | 'PERCENTAGE';
  baby_seat_infant_fee?: number;
  baby_seat_convertible_fee?: number;
  baby_seat_booster_fee?: number;
  max_baby_seats?: number | null;
  minimum_fare?: number;
  currency?: string;
  required_platform_vehicle_ids?: string[];
}
